sonar.projectKey=imanufacto
sonar.projectName=Imanufacto
sonar.projectVersion=1.0

# Path to source directories (comma-separated)
sonar.sources=src

# Path to test directories (comma-separated)
# sonar.tests=src/tests

# List of file encodings
sonar.sourceEncoding=UTF-8

# Exclusions
sonar.exclusions=**/node_modules/**,**/.next/**,**/drizzle/**,**/public/**,**/coverage/**,**/*.config.ts

# TypeScript specific
sonar.typescript.lcov.reportPaths=coverage/lcov.info
