import 'dotenv/config'; // Load .env
import fs from 'fs';
import path from 'path';
import dotenv from 'dotenv';
import { eq } from 'drizzle-orm';
import { reports } from './schema';

// 1. Load Environment Variables properly BEFORE importing db
const envLocalPath = path.resolve(process.cwd(), '.env.local');
if (fs.existsSync(envLocalPath)) {
  console.log('Loading .env.local');
  dotenv.config({ path: envLocalPath });
}

// 2. Dynamic import of db to ensure process.env is populated
async function getDb() {
  const { db } = await import('./index');
  return db;
}

// --- STANDARD HEADER & FOOTER ---

const sampleHeader = `
  <div style="display: flex; justify-content: space-between; align-items: center; border-bottom: 2px solid #2c3e50; padding-bottom: 15px; margin-bottom: 25px;">
    <div style="display: flex; align-items: center;">
       <!-- Logo Placeholder -->
       <div style="width: 40px; height: 40px; background-color: #3498db; border-radius: 5px; margin-right: 15px; display: flex; align-items: center; justify-content: center; color: white; font-weight: bold; font-family: sans-serif;">IM</div>
       <div>
          <h1 style="margin: 0; color: #2c3e50; font-size: 22px; font-family: sans-serif;">imanufacto</h1>
          <span style="font-size: 12px; color: #7f8c8d; font-family: sans-serif;">Excellence in Management Systems</span>
       </div>
    </div>
    <div style="text-align: right; font-size: 12px; color: #555; font-family: sans-serif;">
      <p style="margin: 2px 0;">Report Date: ${new Date().toLocaleDateString()}</p>
      <p style="margin: 2px 0;">Generated by: System</p>
    </div>
  </div>
`;

const sampleFooter = `
  <div style="border-top: 1px solid #ccc; padding-top: 15px; margin-top: 40px; display: flex; justify-content: space-between; font-size: 10px; color: #999; font-family: sans-serif;">
    <span>Confidential - Internal Use Only</span>
    <span>imanufacto QMS/HSE/ISMS System</span>
    <span>Page 1 of 1</span>
  </div>
`;

// --- REPORT TEMPLATES ---

const TEMPLATES: Record<string, string> = {
  // QMS Templates
  DOCUMENTS_CONTROL: `
    <h2 style="color: #2c3e50; font-family: sans-serif;">Master List of Documents</h2>
    <p style="color: #555; font-family: sans-serif;">Current status and revision history of controlled documents.</p>
    
    <table style="width: 100%; border-collapse: collapse; margin-top: 20px; font-family: sans-serif; font-size: 12px;">
      <thead>
        <tr style="background-color: #ecf0f1;">
          <th style="border: 1px solid #bdc3c7; padding: 8px;">Doc ID</th>
          <th style="border: 1px solid #bdc3c7; padding: 8px;">Title</th>
          <th style="border: 1px solid #bdc3c7; padding: 8px;">Rev</th>
          <th style="border: 1px solid #bdc3c7; padding: 8px;">Date</th>
          <th style="border: 1px solid #bdc3c7; padding: 8px;">Owner</th>
          <th style="border: 1px solid #bdc3c7; padding: 8px;">Status</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">QM-001</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Quality Manual</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px; text-align: center;">4.0</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">2024-01-01</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">QA Manager</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px; color: green;">Active</td>
        </tr>
        <tr>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">SOP-PROD-05</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Final Inspection Procedure</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px; text-align: center;">2.1</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">2023-12-15</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Prod Manager</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px; color: green;">Active</td>
        </tr>
      </tbody>
    </table>
  `,

  OBJECTIVE: `
    <h2 style="color: #2c3e50; font-family: sans-serif;">Quality Objectives Report</h2>
    <p style="color: #555; font-family: sans-serif;">Status of organizational quality objectives and performance against targets.</p>
    
    <table style="width: 100%; border-collapse: collapse; margin-top: 20px; font-family: sans-serif; font-size: 12px;">
      <thead>
        <tr style="background-color: #ecf0f1; color: #2c3e50;">
          <th style="border: 1px solid #bdc3c7; padding: 10px; text-align: left;">Objective</th>
          <th style="border: 1px solid #bdc3c7; padding: 10px; text-align: left;">KPI</th>
          <th style="border: 1px solid #bdc3c7; padding: 10px; text-align: center;">Target</th>
          <th style="border: 1px solid #bdc3c7; padding: 10px; text-align: center;">Actual</th>
          <th style="border: 1px solid #bdc3c7; padding: 10px; text-align: left;">Owner</th>
          <th style="border: 1px solid #bdc3c7; padding: 10px; text-align: center;">Status</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Increase Customer Satisfaction</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">CSAT Score</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px; text-align: center;">90%</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px; text-align: center;">88%</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Sales Head</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px; text-align: center; color: orange; font-weight: bold;">At Risk</td>
        </tr>
        <tr>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Reduce Production Defects</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Defect Rate</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px; text-align: center;">&lt; 1%</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px; text-align: center;">0.8%</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Ops Manager</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px; text-align: center; color: green; font-weight: bold;">On Track</td>
        </tr>
        <tr>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">On-Time Delivery</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">% On Time</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px; text-align: center;">98%</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px; text-align: center;">99%</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Logistics</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px; text-align: center; color: green; font-weight: bold;">On Track</td>
        </tr>
      </tbody>
    </table>
  `,

  NON_CONFORMANCE: `
    <h2 style="color: #c0392b; font-family: sans-serif;">Non-Conformance Report (NCR)</h2>
    <p style="color: #555; font-family: sans-serif;">Summary of recent non-conformances, root causes, and corrective actions.</p>

    <table style="width: 100%; border-collapse: collapse; margin-top: 20px; font-family: sans-serif; font-size: 12px;">
      <thead>
        <tr style="background-color: #ecf0f1; color: #2c3e50;">
          <th style="border: 1px solid #bdc3c7; padding: 10px; text-align: left;">NCR ID</th>
          <th style="border: 1px solid #bdc3c7; padding: 10px; text-align: left;">Date</th>
          <th style="border: 1px solid #bdc3c7; padding: 10px; text-align: left;">Description</th>
          <th style="border: 1px solid #bdc3c7; padding: 10px; text-align: left;">Root Cause</th>
          <th style="border: 1px solid #bdc3c7; padding: 10px; text-align: left;">Corrective Action</th>
          <th style="border: 1px solid #bdc3c7; padding: 10px; text-align: center;">Status</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">NCR-2024-001</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">2024-01-10</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Raw material batch #445 failed hardness test.</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Supplier quality issue.</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Returned batch; issued SCAR to supplier.</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px; text-align: center; color: green;">Closed</td>
        </tr>
        <tr>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">NCR-2024-002</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">2024-01-15</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Labeling error on product line B.</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Operator training gap.</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Retrain staff on SOP-LAB-02.</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px; text-align: center; color: orange;">Open</td>
        </tr>
      </tbody>
    </table>
  `,

  RISK_AND_OPPORTUNITY: `
    <h2 style="color: #2c3e50; font-family: sans-serif;">Risk & Opportunity Register</h2>
    <p style="color: #555; font-family: sans-serif;">Overview of identified risks and opportunities in the QMS.</p>

    <h3 style="color: #e67e22; font-family: sans-serif; margin-top: 20px;">Risks</h3>
    <table style="width: 100%; border-collapse: collapse; font-family: sans-serif; font-size: 12px;">
      <thead>
        <tr style="background-color: #fcf3cf; color: #2c3e50;">
          <th style="border: 1px solid #bdc3c7; padding: 8px;">Risk Description</th>
          <th style="border: 1px solid #bdc3c7; padding: 8px;">Impact</th>
          <th style="border: 1px solid #bdc3c7; padding: 8px;">Likelihood</th>
          <th style="border: 1px solid #bdc3c7; padding: 8px;">Mitigation Plan</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Supply chain disruption due to geopolitical issues.</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">High</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Medium</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Identify alternative suppliers in different regions.</td>
        </tr>
      </tbody>
    </table>

    <h3 style="color: #27ae60; font-family: sans-serif; margin-top: 20px;">Opportunities</h3>
    <table style="width: 100%; border-collapse: collapse; font-family: sans-serif; font-size: 12px;">
      <thead>
        <tr style="background-color: #d5f5e3; color: #2c3e50;">
          <th style="border: 1px solid #bdc3c7; padding: 8px;">Opportunity Description</th>
          <th style="border: 1px solid #bdc3c7; padding: 8px;">Potential Benefit</th>
          <th style="border: 1px solid #bdc3c7; padding: 8px;">Action Plan</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Automation of packaging line.</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Reduce cost by 15%, increase speed.</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Conduct ROI analysis by Q2.</td>
        </tr>
      </tbody>
    </table>
  `,

  TRAINING: `
    <h2 style="color: #2c3e50; font-family: sans-serif;">Training Record</h2>
    <p style="color: #555; font-family: sans-serif;">Record of employee training and competence evaluation.</p>
    
    <table style="width: 100%; border-collapse: collapse; margin-top: 20px; font-family: sans-serif; font-size: 12px;">
      <thead>
        <tr style="background-color: #ecf0f1;">
          <th style="border: 1px solid #bdc3c7; padding: 8px;">Employee Name</th>
          <th style="border: 1px solid #bdc3c7; padding: 8px;">Department</th>
          <th style="border: 1px solid #bdc3c7; padding: 8px;">Training Topic</th>
          <th style="border: 1px solid #bdc3c7; padding: 8px;">Date</th>
          <th style="border: 1px solid #bdc3c7; padding: 8px;">Result</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">John Doe</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Production</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Machine Safety L1</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">2024-01-20</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px; color: green;">Pass</td>
        </tr>
        <tr>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Jane Smith</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Quality</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">ISO 9001 Awareness</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">2024-02-05</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px; color: green;">Pass</td>
        </tr>
      </tbody>
    </table>
  `,

  SUPPLIER: `
    <h2 style="color: #2c3e50; font-family: sans-serif;">Supplier Performance Report</h2>
    
    <table style="width: 100%; border-collapse: collapse; margin-top: 20px; font-family: sans-serif; font-size: 12px;">
      <thead>
        <tr style="background-color: #ecf0f1;">
          <th style="border: 1px solid #bdc3c7; padding: 8px;">Supplier Name</th>
          <th style="border: 1px solid #bdc3c7; padding: 8px;">Category</th>
          <th style="border: 1px solid #bdc3c7; padding: 8px;">Quality Rating</th>
          <th style="border: 1px solid #bdc3c7; padding: 8px;">Delivery Rating</th>
          <th style="border: 1px solid #bdc3c7; padding: 8px;">Overall Status</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Acme Corp</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Raw Materials</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px; text-align: center;">4.5/5</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px; text-align: center;">4.0/5</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px; text-align: center; color: green;">Approved</td>
        </tr>
        <tr>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Globex Inc</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Packaging</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px; text-align: center;">3.0/5</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px; text-align: center;">2.5/5</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px; text-align: center; color: orange;">Conditional</td>
        </tr>
      </tbody>
    </table>
  `,

  KPI_REPORT: `
    <h2 style="color: #2c3e50; font-family: sans-serif;">Key Performance Indicators (KPI)</h2>
    
    <div style="display: flex; gap: 20px; margin-bottom: 20px;">
      <div style="flex: 1; border: 1px solid #ddd; padding: 15px; border-radius: 5px; text-align: center; font-family: sans-serif;">
        <h3 style="margin: 0; color: #7f8c8d; font-size: 14px;">Total Production</h3>
        <p style="font-size: 24px; font-weight: bold; color: #2c3e50; margin: 10px 0;">1,250 Units</p>
        <span style="color: green; font-size: 12px;">▲ 5% vs last month</span>
      </div>
      <div style="flex: 1; border: 1px solid #ddd; padding: 15px; border-radius: 5px; text-align: center; font-family: sans-serif;">
        <h3 style="margin: 0; color: #7f8c8d; font-size: 14px;">Downtime</h3>
        <p style="font-size: 24px; font-weight: bold; color: #c0392b; margin: 10px 0;">4.5 Hours</p>
        <span style="color: red; font-size: 12px;">▲ 1.2% vs last month</span>
      </div>
       <div style="flex: 1; border: 1px solid #ddd; padding: 15px; border-radius: 5px; text-align: center; font-family: sans-serif;">
        <h3 style="margin: 0; color: #7f8c8d; font-size: 14px;">Safety Incidents</h3>
        <p style="font-size: 24px; font-weight: bold; color: #27ae60; margin: 10px 0;">0</p>
        <span style="color: green; font-size: 12px;">Target Achieved</span>
      </div>
    </div>
  `,

  // HSE Templates
  HAZARD_AND_RISK: `
    <h2 style="color: #d35400; font-family: sans-serif;">Hazard Identification & Risk Assessment</h2>
    
    <table style="width: 100%; border-collapse: collapse; margin-top: 20px; font-family: sans-serif; font-size: 11px;">
      <thead>
        <tr style="background-color: #f6ddcc; color: #d35400;">
          <th style="border: 1px solid #e59866; padding: 8px;">Activity</th>
          <th style="border: 1px solid #e59866; padding: 8px;">Hazard</th>
          <th style="border: 1px solid #e59866; padding: 8px;">Risk (SxL)</th>
          <th style="border: 1px solid #e59866; padding: 8px;">Existing Controls</th>
          <th style="border: 1px solid #e59866; padding: 8px;">Residual Risk</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="border: 1px solid #e59866; padding: 8px;">Welding Operations</td>
          <td style="border: 1px solid #e59866; padding: 8px;">Toxic Fumes, Fire</td>
          <td style="border: 1px solid #e59866; padding: 8px; background-color: #e74c3c; color: white; text-align: center;">High (15)</td>
          <td style="border: 1px solid #e59866; padding: 8px;">Fume extractors, PPE, Fire Extinguisher</td>
          <td style="border: 1px solid #e59866; padding: 8px; text-align: center;">Medium (6)</td>
        </tr>
        <tr>
          <td style="border: 1px solid #e59866; padding: 8px;">Forklift Driving</td>
          <td style="border: 1px solid #e59866; padding: 8px;">Collision, Overturning</td>
          <td style="border: 1px solid #e59866; padding: 8px; background-color: #f39c12; color: white; text-align: center;">Medium (9)</td>
          <td style="border: 1px solid #e59866; padding: 8px;">Speed limiters, Designated lanes, Training</td>
          <td style="border: 1px solid #e59866; padding: 8px; text-align: center;">Low (3)</td>
        </tr>
      </tbody>
    </table>
  `,

  ACCIDENT_INCIDENT: `
    <h2 style="color: #c0392b; font-family: sans-serif;">Accident / Incident Report</h2>
    
    <div style="border: 1px solid #ddd; padding: 15px; margin-bottom: 15px; background-color: #f9f9f9; font-family: sans-serif; font-size: 12px;">
      <h3 style="margin-top: 0;">Incident #INC-2024-05</h3>
      <p><strong>Date/Time:</strong> 2024-02-01 10:30 AM</p>
      <p><strong>Location:</strong> Warehouse Zone B</p>
      <p><strong>Type:</strong> Near Miss</p>
      <p><strong>Description:</strong> Pallet stacked too high tipped over. No injuries reported.</p>
      <p><strong>Root Cause:</strong> Failure to follow stacking height guidelines.</p>
      <p><strong>Corrective Action:</strong> Retraining on safe stacking procedures. Signage updated.</p>
    </div>
  `,

  EMERGENCY_DRILL: `
    <h2 style="color: #2c3e50; font-family: sans-serif;">Emergency Drill Record</h2>
    
    <table style="width: 100%; border-collapse: collapse; margin-top: 20px; font-family: sans-serif; font-size: 12px;">
      <thead>
        <tr style="background-color: #ecf0f1;">
          <th style="border: 1px solid #bdc3c7; padding: 8px;">Date</th>
          <th style="border: 1px solid #bdc3c7; padding: 8px;">Drill Type</th>
          <th style="border: 1px solid #bdc3c7; padding: 8px;">Evacuation Time</th>
          <th style="border: 1px solid #bdc3c7; padding: 8px;">Observations</th>
          <th style="border: 1px solid #bdc3c7; padding: 8px;">Action Items</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">2024-01-15</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Fire Evacuation</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">4 mins 30 sec</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Assembly point B was crowded.</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Expand assembly area.</td>
        </tr>
      </tbody>
    </table>
  `,

  EMERGENCY_PLAN: `
    <h2 style="color: #8e44ad; font-family: sans-serif;">Emergency Response Plan</h2>
    <p style="color: #555; font-family: sans-serif;">Approved emergency plans and response procedures.</p>

    <table style="width: 100%; border-collapse: collapse; margin-top: 20px; font-family: sans-serif; font-size: 12px;">
      <thead>
        <tr style="background-color: #f4ecf7; color: #8e44ad;">
          <th style="border: 1px solid #d2b4de; padding: 8px;">Plan ID</th>
          <th style="border: 1px solid #d2b4de; padding: 8px;">Emergency Type</th>
          <th style="border: 1px solid #d2b4de; padding: 8px;">Key Response Actions</th>
          <th style="border: 1px solid #d2b4de; padding: 8px;">Responsible Team</th>
          <th style="border: 1px solid #d2b4de; padding: 8px;">Last Reviewed</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="border: 1px solid #d2b4de; padding: 8px;">ERP-001</td>
          <td style="border: 1px solid #d2b4de; padding: 8px;">Chemical Spill</td>
          <td style="border: 1px solid #d2b4de; padding: 8px;">1. Evacuate area.<br>2. Contain spill with kit.<br>3. Notify HSE Lead.</td>
          <td style="border: 1px solid #d2b4de; padding: 8px;">HazMat Team</td>
          <td style="border: 1px solid #d2b4de; padding: 8px;">2023-11-20</td>
        </tr>
        <tr>
          <td style="border: 1px solid #d2b4de; padding: 8px;">ERP-002</td>
          <td style="border: 1px solid #d2b4de; padding: 8px;">Medical Emergency</td>
          <td style="border: 1px solid #d2b4de; padding: 8px;">1. Call First Aider.<br>2. Call Ambulance if critical.<br>3. Clear access route.</td>
          <td style="border: 1px solid #d2b4de; padding: 8px;">First Aiders</td>
          <td style="border: 1px solid #d2b4de; padding: 8px;">2024-01-05</td>
        </tr>
      </tbody>
    </table>
  `,

  // ISMS Templates
  STATEMENT_OF_APPLICABILITY: `
    <h2 style="color: #2980b9; font-family: sans-serif;">Statement of Applicability (SoA)</h2>
    <p style="color: #555; font-family: sans-serif;">ISO 27001 Annex A Control Implementation Status.</p>
    
    <table style="width: 100%; border-collapse: collapse; margin-top: 20px; font-family: sans-serif; font-size: 11px;">
      <thead>
        <tr style="background-color: #d6eaf8; color: #2980b9;">
          <th style="border: 1px solid #a9cce3; padding: 8px;">ID</th>
          <th style="border: 1px solid #a9cce3; padding: 8px;">Control</th>
          <th style="border: 1px solid #a9cce3; padding: 8px;">Applicable?</th>
          <th style="border: 1px solid #a9cce3; padding: 8px;">Justification</th>
          <th style="border: 1px solid #a9cce3; padding: 8px;">Implementation Status</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="border: 1px solid #a9cce3; padding: 8px;">A.5.1</td>
          <td style="border: 1px solid #a9cce3; padding: 8px;">Policies for information security</td>
          <td style="border: 1px solid #a9cce3; padding: 8px; text-align: center;">Yes</td>
          <td style="border: 1px solid #a9cce3; padding: 8px;">Legal & Business Requirement</td>
          <td style="border: 1px solid #a9cce3; padding: 8px;">Implemented</td>
        </tr>
        <tr>
          <td style="border: 1px solid #a9cce3; padding: 8px;">A.8.2</td>
          <td style="border: 1px solid #a9cce3; padding: 8px;">Privileged access rights</td>
          <td style="border: 1px solid #a9cce3; padding: 8px; text-align: center;">Yes</td>
          <td style="border: 1px solid #a9cce3; padding: 8px;">Prevent unauthorized system changes</td>
          <td style="border: 1px solid #a9cce3; padding: 8px;">Implemented</td>
        </tr>
         <tr>
          <td style="border: 1px solid #a9cce3; padding: 8px;">A.14.1</td>
          <td style="border: 1px solid #a9cce3; padding: 8px;">Information security in development</td>
          <td style="border: 1px solid #a9cce3; padding: 8px; text-align: center;">No</td>
          <td style="border: 1px solid #a9cce3; padding: 8px;">No internal software development</td>
          <td style="border: 1px solid #a9cce3; padding: 8px;">N/A</td>
        </tr>
      </tbody>
    </table>
  `,

  ISMS_RISK: `
    <h2 style="color: #2980b9; font-family: sans-serif;">Information Security Risk Assessment</h2>
    
    <table style="width: 100%; border-collapse: collapse; margin-top: 20px; font-family: sans-serif; font-size: 11px;">
      <thead>
        <tr style="background-color: #d6eaf8; color: #2980b9;">
          <th style="border: 1px solid #a9cce3; padding: 8px;">Asset</th>
          <th style="border: 1px solid #a9cce3; padding: 8px;">Threat</th>
          <th style="border: 1px solid #a9cce3; padding: 8px;">Vulnerability</th>
          <th style="border: 1px solid #a9cce3; padding: 8px;">Risk Level</th>
          <th style="border: 1px solid #a9cce3; padding: 8px;">Treatment</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="border: 1px solid #a9cce3; padding: 8px;">Customer Database</td>
          <td style="border: 1px solid #a9cce3; padding: 8px;">Data Breach / Theft</td>
          <td style="border: 1px solid #a9cce3; padding: 8px;">Weak password policy</td>
          <td style="border: 1px solid #a9cce3; padding: 8px; color: red; font-weight: bold;">High</td>
          <td style="border: 1px solid #a9cce3; padding: 8px;">Enforce MFA and complex passwords</td>
        </tr>
        <tr>
          <td style="border: 1px solid #a9cce3; padding: 8px;">Company Laptops</td>
          <td style="border: 1px solid #a9cce3; padding: 8px;">Theft / Loss</td>
          <td style="border: 1px solid #a9cce3; padding: 8px;">Lack of encryption</td>
          <td style="border: 1px solid #a9cce3; padding: 8px; color: orange; font-weight: bold;">Medium</td>
          <td style="border: 1px solid #a9cce3; padding: 8px;">Implement Full Disk Encryption (BitLocker)</td>
        </tr>
      </tbody>
    </table>
  `,

  ISMS_ASSET: `
    <h2 style="color: #2c3e50; font-family: sans-serif;">Information Asset Inventory</h2>
    
    <table style="width: 100%; border-collapse: collapse; margin-top: 20px; font-family: sans-serif; font-size: 12px;">
      <thead>
        <tr style="background-color: #ecf0f1;">
          <th style="border: 1px solid #bdc3c7; padding: 8px;">Asset Name</th>
          <th style="border: 1px solid #bdc3c7; padding: 8px;">Type</th>
          <th style="border: 1px solid #bdc3c7; padding: 8px;">Owner</th>
          <th style="border: 1px solid #bdc3c7; padding: 8px;">Classification</th>
          <th style="border: 1px solid #bdc3c7; padding: 8px;">Location</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Production Server</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Hardware</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">IT Manager</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Confidential</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Server Room</td>
        </tr>
        <tr>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Source Code</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Information</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">CTO</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Strictly Confidential</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Git Repository</td>
        </tr>
      </tbody>
    </table>
  `,

  BUSINESS_CONTINUITY: `
    <h2 style="color: #2c3e50; font-family: sans-serif;">Business Continuity Plan</h2>
    <p style="color: #555; font-family: sans-serif;">Strategies for maintaining business operations during disruptions.</p>
    
    <table style="width: 100%; border-collapse: collapse; margin-top: 20px; font-family: sans-serif; font-size: 12px;">
      <thead>
        <tr style="background-color: #ecf0f1;">
          <th style="border: 1px solid #bdc3c7; padding: 8px;">Critical Process</th>
          <th style="border: 1px solid #bdc3c7; padding: 8px;">RTO (Time)</th>
          <th style="border: 1px solid #bdc3c7; padding: 8px;">RPO (Data Loss)</th>
          <th style="border: 1px solid #bdc3c7; padding: 8px;">Recovery Strategy</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Customer Orders</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">4 Hours</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">1 Hour</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Switch to redundant cloud server.</td>
        </tr>
        <tr>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Email Communication</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">8 Hours</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">4 Hours</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Use failover mail service.</td>
        </tr>
      </tbody>
    </table>
  `,

  ISMS_INCIDENT: `
    <h2 style="color: #c0392b; font-family: sans-serif;">Information Security Incidents</h2>
    
    <table style="width: 100%; border-collapse: collapse; margin-top: 20px; font-family: sans-serif; font-size: 12px;">
      <thead>
        <tr style="background-color: #f2d7d5; color: #c0392b;">
          <th style="border: 1px solid #e6b0aa; padding: 8px;">Incident ID</th>
          <th style="border: 1px solid #e6b0aa; padding: 8px;">Date</th>
          <th style="border: 1px solid #e6b0aa; padding: 8px;">Description</th>
          <th style="border: 1px solid #e6b0aa; padding: 8px;">Severity</th>
          <th style="border: 1px solid #e6b0aa; padding: 8px;">Resolution</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="border: 1px solid #e6b0aa; padding: 8px;">SEC-2024-003</td>
          <td style="border: 1px solid #e6b0aa; padding: 8px;">2024-02-10</td>
          <td style="border: 1px solid #e6b0aa; padding: 8px;">Phishing email campaign targeted employees.</td>
          <td style="border: 1px solid #e6b0aa; padding: 8px; color: red;">High</td>
          <td style="border: 1px solid #e6b0aa; padding: 8px;">Emails blocked; staff alerted.</td>
        </tr>
      </tbody>
    </table>
  `,

  // FSMS Templates
  CCP_MONITORING: `
    <h2 style="color: #27ae60; font-family: sans-serif;">CCP Monitoring Report</h2>
    <p style="color: #555; font-family: sans-serif;">Critical Control Point (CCP) monitoring logs.</p>
    
    <table style="width: 100%; border-collapse: collapse; margin-top: 20px; font-family: sans-serif; font-size: 12px;">
      <thead>
        <tr style="background-color: #d5f5e3; color: #27ae60;">
          <th style="border: 1px solid #a9dfbf; padding: 8px;">CCP ID</th>
          <th style="border: 1px solid #a9dfbf; padding: 8px;">Process Step</th>
          <th style="border: 1px solid #a9dfbf; padding: 8px;">Critical Limit</th>
          <th style="border: 1px solid #a9dfbf; padding: 8px;">Measured Value</th>
          <th style="border: 1px solid #a9dfbf; padding: 8px;">Result</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="border: 1px solid #a9dfbf; padding: 8px;">CCP-1</td>
          <td style="border: 1px solid #a9dfbf; padding: 8px;">Pasteurization</td>
          <td style="border: 1px solid #a9dfbf; padding: 8px;">Temp >= 72°C for 15s</td>
          <td style="border: 1px solid #a9dfbf; padding: 8px;">74°C / 16s</td>
          <td style="border: 1px solid #a9dfbf; padding: 8px; color: green;">Pass</td>
        </tr>
      </tbody>
    </table>
  `,

  HYGIENE_INSPECTION: `
    <h2 style="color: #27ae60; font-family: sans-serif;">Hygiene Inspection Report</h2>
    
    <table style="width: 100%; border-collapse: collapse; margin-top: 20px; font-family: sans-serif; font-size: 12px;">
      <thead>
        <tr style="background-color: #d5f5e3; color: #27ae60;">
          <th style="border: 1px solid #a9dfbf; padding: 8px;">Area</th>
          <th style="border: 1px solid #a9dfbf; padding: 8px;">Checklist Item</th>
          <th style="border: 1px solid #a9dfbf; padding: 8px;">Status</th>
          <th style="border: 1px solid #a9dfbf; padding: 8px;">Remarks</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="border: 1px solid #a9dfbf; padding: 8px;">Kitchen</td>
          <td style="border: 1px solid #a9dfbf; padding: 8px;">Surfaces Clean/Sanitized</td>
          <td style="border: 1px solid #a9dfbf; padding: 8px;">Pass</td>
          <td style="border: 1px solid #a9dfbf; padding: 8px;">None</td>
        </tr>
      </tbody>
    </table>
  `,

  // IATF Templates
  FMEA_REPORT: `
    <h2 style="color: #2e4053; font-family: sans-serif;">Failure Mode and Effects Analysis (FMEA)</h2>
    
    <table style="width: 100%; border-collapse: collapse; margin-top: 20px; font-family: sans-serif; font-size: 11px;">
      <thead>
        <tr style="background-color: #ebedef; color: #2e4053;">
          <th style="border: 1px solid #bdc3c7; padding: 8px;">Process Step</th>
          <th style="border: 1px solid #bdc3c7; padding: 8px;">Failure Mode</th>
          <th style="border: 1px solid #bdc3c7; padding: 8px;">Effect</th>
          <th style="border: 1px solid #bdc3c7; padding: 8px;">Sev</th>
          <th style="border: 1px solid #bdc3c7; padding: 8px;">Occ</th>
          <th style="border: 1px solid #bdc3c7; padding: 8px;">Det</th>
          <th style="border: 1px solid #bdc3c7; padding: 8px;">RPN</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Stamping</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Burrs on edge</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Injury to assembly worker</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">8</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">4</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">5</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">160</td>
        </tr>
      </tbody>
    </table>
  `,

  CONTROL_PLAN: `
    <h2 style="color: #2e4053; font-family: sans-serif;">Control Plan Status</h2>
    
    <table style="width: 100%; border-collapse: collapse; margin-top: 20px; font-family: sans-serif; font-size: 12px;">
      <thead>
        <tr style="background-color: #ebedef; color: #2e4053;">
          <th style="border: 1px solid #bdc3c7; padding: 8px;">Part Number</th>
          <th style="border: 1px solid #bdc3c7; padding: 8px;">Part Name</th>
          <th style="border: 1px solid #bdc3c7; padding: 8px;">Revision</th>
          <th style="border: 1px solid #bdc3c7; padding: 8px;">Characteristics</th>
          <th style="border: 1px solid #bdc3c7; padding: 8px;">Control Method</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">PN-12345</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Bracket Assembly</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">C</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">Dimensions, Weld Strength</td>
          <td style="border: 1px solid #bdc3c7; padding: 8px;">CMM, Tensile Test</td>
        </tr>
      </tbody>
    </table>
  `,

  // VDA Templates
  VDA_PROCESS_AUDIT: `
    <h2 style="color: #6c3483; font-family: sans-serif;">VDA 6.3 Process Audit</h2>
    
    <div style="margin-bottom: 20px; font-family: sans-serif;">
      <p><strong>Audit Date:</strong> 2024-02-15</p>
      <p><strong>Overall Score:</strong> <span style="color: orange; font-weight: bold;">88% (B)</span></p>
    </div>

    <table style="width: 100%; border-collapse: collapse; margin-top: 20px; font-family: sans-serif; font-size: 12px;">
      <thead>
        <tr style="background-color: #f5eef8; color: #6c3483;">
          <th style="border: 1px solid #d7bde2; padding: 8px;">Question ID</th>
          <th style="border: 1px solid #d7bde2; padding: 8px;">Requirement</th>
          <th style="border: 1px solid #d7bde2; padding: 8px;">Finding</th>
          <th style="border: 1px solid #d7bde2; padding: 8px;">Rating (0-10)</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="border: 1px solid #d7bde2; padding: 8px;">P6.2.1</td>
          <td style="border: 1px solid #d7bde2; padding: 8px;">Is the control plan complete?</td>
          <td style="border: 1px solid #d7bde2; padding: 8px;">Minor deviations in frequency.</td>
          <td style="border: 1px solid #d7bde2; padding: 8px;">8</td>
        </tr>
      </tbody>
    </table>
  `,

  GENERIC: `
    <h2 style="color: #2c3e50; font-family: sans-serif;">Standard Report</h2>
    <p style="color: #555; font-family: sans-serif;">Generated report content.</p>
    
    <div style="border: 1px solid #ddd; padding: 20px; margin-top: 20px; font-family: sans-serif;">
      <p>This report contains standard data items tracked by the system.</p>
      <ul>
        <li>Item 1: Compliant</li>
        <li>Item 2: Reviewed</li>
        <li>Item 3: Pending Approval</li>
      </ul>
    </div>
  `
};

// Map Report Name/Pattern to Template Key
function getTemplateKey(name: string): string {
  const n = name.toUpperCase();
  if (n.includes('OBJECTIVE')) return 'OBJECTIVE';
  if (n.includes('NON CONFORMANCE') || n.includes('NON-CONFORMANCE')) return 'NON_CONFORMANCE';
  if (n.includes('RISK') && n.includes('OPPORTUNITY')) return 'RISK_AND_OPPORTUNITY';
  if (n.includes('TRAINING')) return 'TRAINING';
  if (n.includes('SUPPLIER')) return 'SUPPLIER';
  if (n.includes('KPI')) return 'KPI_REPORT';
  if (n.includes('STATEMENT OF APPLICABILITY')) return 'STATEMENT_OF_APPLICABILITY';
  if (n.includes('HAZARD') || (n.includes('RISK') && n.includes('IDENTIFIED'))) return 'HAZARD_AND_RISK';
  if (n.includes('ACCIDENT') || n.includes('INCIDENT') && !n.includes('ISMS')) return 'ACCIDENT_INCIDENT';
  if (n.includes('DRILL') || n.includes('EMERGENCY') && !n.includes('PLAN')) return 'EMERGENCY_DRILL';
  if (n.includes('EMERGENCY') && n.includes('PLAN')) return 'EMERGENCY_PLAN';
  if (n.includes('ISMS RISK') || n.includes('INFORMATION SECURITY RISK')) return 'ISMS_RISK';
  if (n.includes('ASSET')) return 'ISMS_ASSET';
  if (n.includes('BUSINESS CONTINUITY')) return 'BUSINESS_CONTINUITY';
  if (n.includes('DOCUMENTS')) return 'DOCUMENTS_CONTROL';
  if (n.includes('ISMS') && n.includes('INCIDENT')) return 'ISMS_INCIDENT';
  if (n.includes('CCP')) return 'CCP_MONITORING';
  if (n.includes('HYGIENE')) return 'HYGIENE_INSPECTION';
  if (n.includes('FMEA')) return 'FMEA_REPORT';
  if (n.includes('CONTROL PLAN')) return 'CONTROL_PLAN';
  if (n.includes('VDA')) return 'VDA_PROCESS_AUDIT';
  
  return 'GENERIC';
}

const reportList = [
  { name: 'Statement of Applicability', type: 'PDF v2' },
  { name: 'Hazard and Risk Identified by month', type: 'PDF v2' },
  { name: 'Training', type: 'PDF v2' },
  { name: 'Risk And Opportunity', type: 'PDF v2' },
  { name: 'Hazard and Risk High/Medium', type: 'PDF v2' },
  { name: 'KPI Report', type: 'PDF v2' },
  { name: 'Information Security Risk', type: 'PDF v2' },
  { name: 'Documents', type: 'PDF v2' },
  { name: 'Business Continuity Program', type: 'PDF v2' },
  { name: 'ISMS RISK Analysis Remainder', type: 'HTML' },
  { name: 'Supplier', type: 'PDF v2' },
  { name: 'Emergency drills conducted in current month', type: 'PDF v2' },
  { name: 'Objective', type: 'PDF v2' },
  { name: 'Non Conformance', type: 'PDF v2' },
  { name: 'New emergency plans generated/ prepared', type: 'PDF v2' },
  { name: 'Hazard and Risk by Status', type: 'PDF v2' },
  { name: 'Accident Incidents by status', type: 'PDF v2' },
  { name: 'Accident Incidents by Department', type: 'PDF v2' },
  { name: 'Accident Incidents by month', type: 'PDF v2' },
  { name: 'Accident Incidents in Current month', type: 'PDF v2' },
  { name: 'ISMS Asset', type: 'PDF v2' },
  { name: 'ISMS Incident', type: 'PDF v2' },
  { name: 'CCP Monitoring Report', type: 'PDF v2' },
  { name: 'Hygiene Inspection Report', type: 'PDF v2' },
  { name: 'Process FMEA Report', type: 'PDF v2' },
  { name: 'Control Plan Status', type: 'PDF v2' },
  { name: 'VDA 6.3 Process Audit', type: 'PDF v2' },
];

async function seed() {
  console.log('Seeding reports with industry-standard templates...');
  
  if (!process.env.DATABASE_URL) {
    throw new Error('DATABASE_URL is not defined');
  }

  const db = await getDb();

  for (const report of reportList) {
    const code = report.name.toUpperCase().replace(/[^A-Z0-9]/g, '_');
    const templateKey = getTemplateKey(report.name);
    const templateContent = TEMPLATES[templateKey];

    console.log(`Processing ${report.name} -> Template: ${templateKey}`);

    // Check if exists
    const existing = await db.select()
      .from(reports)
      .where(eq(reports.reportCode, code))
      .limit(1);

    const reportData = {
      reportName: report.name,
      reportCode: code,
      reportType: report.type,
      status: 'Active',
      schedulerStatus: 'Inactive',
      isCurrent: true,
      version: 1,
      templateContent: templateContent,
      headerContent: sampleHeader,
      footerContent: sampleFooter,
      pageSetup: {
        paperFormat: 'A4',
        orientation: 'Portrait',
        headerHeight: 2.5,
        footerHeight: 2,
        margin: 1,
        waitForJavascript: false
      }
    };

    if (existing.length === 0) {
      await db.insert(reports).values(reportData);
    } else {
      await db.update(reports)
        .set(reportData)
        .where(eq(reports.reportCode, code));
    }
  }

  console.log('Reports seeded/updated successfully.');
  process.exit(0);
}

seed().catch((err) => {
  console.error('Seeding failed:', err);
  process.exit(1);
});
